module.exports = {
  defaultSidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "link",
      label: "База знаний",
      href: "pending",
      customProps: { pending: true, label: "Скоро" },
    },
  ],
};
